apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-status-api
  namespace: fiapx
  labels:
    app: video-status-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-status-api
  template:
    metadata:
      labels:
        app: video-status-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8084"
    spec:
      containers:
        - name: video-status-api
          image: video-status-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8084
          env:
            - name: SERVER_PORT
              value: "8084"
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: video-status-config
                  key: AUTH_SERVICE_URL
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_PORT
            - name: RABBITMQ_VHOST
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_VHOST
            - name: RABBITMQ_USER
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_PASSWORD
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-video-status-secret
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-video-status-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-video-status-secret
                  key: SPRING_DATASOURCE_PASSWORD
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8084
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8084
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 6
